name: CI-CD sécurisé avec Snyk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Snyk CLI
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Snyk scan des dépendances Python
        run: |
          snyk test --file=app/requirements.txt --severity-threshold=high

      - name: Build image Docker Flask
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/webapp:latest ./app

      - name: Snyk scan Docker image Flask
        run: |
          snyk container test ${{ secrets.DOCKER_USERNAME }}/webapp:latest --severity-threshold=high --fail-on=never

      - name: Pull Docker MySQL image
        run: |
          docker pull mysql:8.0

      - name: Snyk scan Docker image MySQL
        run: |
          snyk container test mysql:8.0 --severity-threshold=high

      - name: Push Flask image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/webapp:latest
